-- 채팅방
CREATE TABLE chat_room (
    chat_room_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member1_id      BIGINT NOT NULL REFERENCES member(member_id),
    member2_id      BIGINT NOT NULL REFERENCES member(member_id),
    member1_left    BOOLEAN NOT NULL DEFAULT FALSE,
    member2_left    BOOLEAN NOT NULL DEFAULT FALSE,
    member1_left_at TIMESTAMP(6),
    member2_left_at TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT uq_chat_room_members UNIQUE (member1_id, member2_id),
    CONSTRAINT chk_chat_room_member_order CHECK (member1_id < member2_id)
);

CREATE INDEX idx_chat_room_member1 ON chat_room(member1_id);
CREATE INDEX idx_chat_room_member2 ON chat_room(member2_id);

-- 채팅 메시지
CREATE TABLE chat_message (
    chat_message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id    BIGINT NOT NULL REFERENCES chat_room(chat_room_id),
    sender_id       BIGINT NOT NULL REFERENCES member(member_id),
    content         VARCHAR(1000) NOT NULL,
    is_read         BOOLEAN NOT NULL DEFAULT FALSE,
    read_at         TIMESTAMP(6),
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE INDEX idx_chat_message_room_created ON chat_message(chat_room_id, created_at DESC);
CREATE INDEX idx_chat_message_unread ON chat_message(chat_room_id, sender_id, is_read)
    WHERE is_read = FALSE;
