-- 신고 처리 이력 로그
CREATE TABLE complaint_history (
    complaint_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_id          BIGINT NOT NULL REFERENCES complaint(complaint_id),
    status                VARCHAR(20) NOT NULL,
    action                VARCHAR(20),
    resolution_reason     TEXT,
    resolver_member_id    BIGINT REFERENCES member(member_id),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6),
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255)
);

CREATE INDEX idx_complaint_history_complaint ON complaint_history(complaint_id, created_at);
