-- 관리자 유저 관리: 계정 정지/강제탈퇴 예정 상태 추가
ALTER TABLE member DROP CONSTRAINT member_used_check;

ALTER TABLE member ADD CONSTRAINT member_used_check
    CHECK (((used)::text = ANY (ARRAY[
        ('ACTIVE'::character varying)::text,
        ('INACTIVE'::character varying)::text,
        ('SUSPENDED'::character varying)::text,
        ('PENDING_WITHDRAWAL'::character varying)::text,
        ('DELETED'::character varying)::text
    ])));

ALTER TABLE member ADD COLUMN scheduled_withdrawal_at TIMESTAMP(6);

-- 관리자 유저 상태 변경(정지/정지해제/강제탈퇴) 이력
CREATE TABLE member_status_history (
    member_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id             BIGINT NOT NULL REFERENCES member(member_id),
    action                VARCHAR(20) NOT NULL,
    status                VARCHAR(20) NOT NULL,
    reason                TEXT,
    notify_requested      BOOLEAN NOT NULL DEFAULT FALSE,
    scheduled_withdrawal_at TIMESTAMP(6),
    processor_member_id   BIGINT REFERENCES member(member_id),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6),
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255)
);

CREATE INDEX idx_member_status_history_member ON member_status_history(member_id, created_at);

-- 관리자 유저 상세조회용 로그인 이력
CREATE TABLE member_login_history (
    member_login_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id             BIGINT NOT NULL REFERENCES member(member_id),
    login_at              TIMESTAMP(6) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6),
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255)
);

CREATE INDEX idx_member_login_history_member ON member_login_history(member_id, login_at);
