CREATE TABLE IF NOT EXISTS nickname_history (
    nickname_history_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id           bigint                              NOT NULL,
    previous_nickname   varchar(20)                         NOT NULL,
    created_at          timestamp(6) without time zone      NOT NULL,
    CONSTRAINT fk_nickname_history_member
        FOREIGN KEY (member_id) REFERENCES member (member_id)
);

CREATE INDEX idx_nickname_history_member_id ON nickname_history (member_id);
