-- 회원 자진 탈퇴 시 잔여 리포트 생성권 환불 신청 레코드
CREATE TABLE credit_refund_request (
    credit_refund_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                BIGINT NOT NULL REFERENCES member(member_id),
    credit_amount_at_request INTEGER NOT NULL,
    status                   VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    requested_at             TIMESTAMP(6) NOT NULL,
    processed_at             TIMESTAMP(6),
    processor_member_id      BIGINT REFERENCES member(member_id),
    created_at               TIMESTAMP(6) NOT NULL,
    updated_at               TIMESTAMP(6),
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255)
);

CREATE INDEX idx_credit_refund_request_status ON credit_refund_request(status);
