-- 강제탈퇴자 재가입 제한 대조용 이메일 해시 블랙리스트 (이용약관 제5조 3항)
CREATE TABLE withdrawn_member_email_hash (
    withdrawn_member_email_hash_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_hash    VARCHAR(64) NOT NULL,
    withdrawn_at  TIMESTAMP(6) NOT NULL,
    expires_at    TIMESTAMP(6) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6),
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255)
);

CREATE INDEX idx_withdrawn_member_email_hash_hash ON withdrawn_member_email_hash(email_hash);
