-- 관리자 신고/제재 관리
CREATE TABLE complaint (
    complaint_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complainant_member_id    BIGINT NOT NULL REFERENCES member(member_id),
    respondent_member_id    BIGINT NOT NULL REFERENCES member(member_id),
    target_type           VARCHAR(20) NOT NULL,
    target_id             BIGINT,
    reason                TEXT NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    action                VARCHAR(20),
    resolution_reason     TEXT,
    resolver_member_id    BIGINT REFERENCES member(member_id),
    resolved_at           TIMESTAMP(6),
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6),
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255)
);

CREATE INDEX idx_complaint_respondent_member ON complaint(respondent_member_id);
CREATE INDEX idx_complaint_status_created ON complaint(status, created_at);
