name: CI - Realtime

on:
  workflow_dispatch:
  push:
    branches: [ main, qa ]
    paths:
      - 'devine-realtime/**'
      - 'devine-core/**'
      - 'build.gradle'
      - 'settings.gradle'
      - 'gradle/**'
      - '.github/workflows/ci-realtime.yml'
      - '.github/workflows/cd-realtime.yml'
      - '.github/actions/ci-build/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ci-build
        with:
          module: devine-realtime
          test-modules: ':devine-core:test :devine-realtime:test'
          docker-image-name: devine-realtime
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
